name: Cache Dependencies Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/dependencies
          key: cache-f8540ad

      - name: prime-cache-f8540ad
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
